adding perms to grant read and put to clients dir on s3
opensearch-project/opensearch-build pull request #1219
Opened 2021-12-01 22:18 UTC by abhinavGupta16

Signed-off-by: Abhinav Gupta <abhng@amazon.com>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-12-01 22:26 UTC, gaiksaya approved these changes

2021-12-01 22:39 UTC, peternied requested changes
Why are we adding a client bucket?

2021-12-01 22:40 UTC, peternied commented
> Why are we adding a client bucket?

It seems like we should be pushing the artifacts into the `build` folder

2021-12-01 22:42 UTC, gaiksaya commented
> Why are we adding a client bucket?

Don't we cant to keep bundle builds and clients build separate?
I think its much cleaner and less confusing.

2021-12-01 22:45 UTC, zelinh approved these changes
I think it would be better if we have builds & clients separate. Be sure we deploy this change after merge.

2021-12-01 22:45 UTC, peternied commented
> > Why are we adding a client bucket?
> 
> Don't we want to keep bundle builds and clients build separate? I think its much cleaner and less confusing. Inside clients we would have folders per client basis (is at all required) like `opensearch-ruby`

All jenkins jobs should have their own top level s3 bucket so there is no possible intersection, is there a reason this isolation should be removed?

2021-12-01 22:47 UTC, abhinavGupta16 commented
> > > Why are we adding a client bucket?
> > 
> > 
> > Don't we want to keep bundle builds and clients build separate? I think its much cleaner and less confusing. Inside clients we would have folders per client basis (is at all required) like `opensearch-ruby`
> 
> All jenkins jobs should have their own top level s3 bucket so there is no possible intersection, is there a reason this isolation should be removed?

I believe eventually with the number of clients increasing, it will be easier to manage in the future to have all the clients in one place. Each job having the same top level bucket may become messy later on. Thoughts?

2021-12-01 22:47 UTC, gaiksaya commented
> > > Why are we adding a client bucket?
> > 
> > 
> > Don't we want to keep bundle builds and clients build separate? I think its much cleaner and less confusing. Inside clients we would have folders per client basis (is at all required) like `opensearch-ruby`
> 
> All jenkins jobs should have their own top level s3 bucket so there is no possible intersection, is there a reason this isolation should be removed?

Are you saying each client should have their own bucket? That sounds good too. In that case @abhinavGupta16 would need to make changes to cdk to accommodate this. Along with new role that has access only to that bucket.

2021-12-01 22:52 UTC, peternied commented
> Are you saying each client should have their own bucket? That sounds good too. In that case @abhinavGupta16 would need to make changes to cdk to accommodate this. Along with new role that has access only to that bucket.

Here is how it looks today:

- BundleBuild
  - https://ci.opensearch.org/ci/dbc/bundle-build/2.0.0/1240/linux/arm64/builds/...
- BundleBuildDashboards
  - https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/2.0.0/1240/linux/arm64/builds/...

I am proposing we do _not change anything_ with our current artifact management process, this change could be
- OpenSearch-Ruby
  - https://ci.opensearch.org/ci/dbc/opensearch-ruby/1.2.0/17/linux/arm64/builds/...

2021-12-01 22:59 UTC, abhinavGupta16 commented
> > > > Why are we adding a client bucket?
> > > 
> > > 
> > > Don't we want to keep bundle builds and clients build separate? I think its much cleaner and less confusing. Inside clients we would have folders per client basis (is at all required) like `opensearch-ruby`
> > 
> > 
> > All jenkins jobs should have their own top level s3 bucket so there is no possible intersection, is there a reason this isolation should be removed?
> 
> Are you saying each client should have their own bucket? That sounds good too. In that case @abhinavGupta16 would need to make changes to cdk to accommodate this. Along with new role that has access only to that bucket.

Won't that become too many roles as clients increase? It would be great if it would restrict other clients to be able to use the role? The way I see it, people can simply use the role they want and Jenkins would have permission to use and upload it.

2021-12-01 23:01 UTC, abhinavGupta16 commented
> > Are you saying each client should have their own bucket? That sounds good too. In that case @abhinavGupta16 would need to make changes to cdk to accommodate this. Along with new role that has access only to that bucket.
> 
> Here is how it looks today:
> 
> * BundleBuild
>   
>   * https://ci.opensearch.org/ci/dbc/bundle-build/2.0.0/1240/linux/arm64/builds/...
> * BundleBuildDashboards
>   
>   * https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/2.0.0/1240/linux/arm64/builds/...
> 
> I am proposing we do _not change anything_ with our current artifact management process, the new job would could have a path like this
> 
> * OpenSearch-Ruby
>   
>   * https://ci.opensearch.org/ci/dbc/opensearch-ruby/1.2.0/17/linux/arm64/builds/...
> 
> FYI @abhinavGupta16

I see your point. Looking in the future, what happens when the number of clients increase? Wouldn’t it become a problem to look them up since all will be present in the root dir?

2021-12-01 23:20 UTC, peternied commented
> However, looking into the future, what happens when the number of clients increase?

Each client should have their own deployment configuration, if this number is sufficiently larger we will need to find a way to shard them, assuming we know how to divide them up I think we can just deploy a fresh Jenkins stamp with the existing bucket management tools.

2021-12-01 23:22 UTC, peternied commented
> problem to look them up since all will be present in the root dir

We should not be 'looking' at a directory for these proceses, that is an error prone process.  We will need automation that takes the results of the build process and then publishes.  We have the very begining of this for the OpenSearch service but we will need to advance this to support the large number of clients we have and will continue to have

2021-12-01 23:28 UTC, dblock reviewed
What's special about "clients"? Shouldn't that be `builds/<product name>/...` or `dist/<product name>/...`?

2021-12-01 23:54 UTC, abhinavGupta16 commented
I believe It's a design question that needs to be visited and discussed properly to see which solution is scalable and which solution works best for our org. I have created an issue for this - #1223

Since this issue needs perms now for deployment and release for rubygems, what should we do in the meantime here? Can we simply go ahead with this? @peternied @gaiksaya @zelinh @peterzhuamazon @dblock

2021-12-02 01:35 UTC, dblock commented
> I believe It's a design question that needs to be visited and discussed properly to see which solution is scalable and which solution works best for our org as we grow in size. I have created an issue for this - #1223
> 
> Since this issue needs perms now for deployment and release for rubygems, what should we do in the meantime here? Can we simply go ahead with this? @peternied @gaiksaya @zelinh @peterzhuamazon @dblock

Adding `clients` is my least favorite option. We already have a pattern with `job-name/version/build-number/platform/architecture/builds|dist`. Why do we need to add `clients` to it?

2021-12-02 18:23 UTC, abhinavGupta16 commented
> > I believe It's a design question that needs to be visited and discussed properly to see which solution is scalable and which solution works best for our org as we grow in size. I have created an issue for this - #1223
> > Since this issue needs perms now for deployment and release for rubygems, what should we do in the meantime here? Can we simply go ahead with this? @peternied @gaiksaya @zelinh @peterzhuamazon @dblock
> 
> Adding `clients` is my least favorite option. We already have a pattern with `job-name/version/build-number/platform/architecture/builds|dist/product-name`. Why do we need to add `clients` to it?

We can put it in `builds` as well, however, we don't have specific platform or architecture associated with these. Therefore, not sure why we need them.

2021-12-02 19:00 UTC, dblock commented
> We can put it in `builds` as well, however, we don't have specific platform or architecture associated with these. Therefore, not sure why we need them.

In general ruby gems can target irb vs. jruby, so double-check whether we have any kind of such variation.

2021-12-02 20:40 UTC, abhinavGupta16 commented
`BUCKET/JOB_NAME/VERSION/build` was decided as the path for s3.

2021-12-02 20:40 UTC, closed without merging