Update public url to include product name
opensearch-project/opensearch-build pull request #1265
Opened 2021-12-07 01:54 UTC by tianleh

### Description
The public url has the product as sub dir. Thus we need to include it to access the content.
 
### Issues Resolved
Resolves https://github.com/opensearch-project/opensearch-build/issues/1264
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-12-07 03:33 UTC, seraphjiang approved these changes

2021-12-07 12:38 UTC, peternied reviewed
> Thus we need to include it to access the content.

Please provide background for this change, its a breaking change to the url schema

2021-12-07 12:39 UTC, peternied requested changes
Why isn't the `job-name-opensearch` part of the url sufficiently unique?

2021-12-07 14:01 UTC, dblock requested changes
This isn't the product or product name (that would be `OpenSearch` or `OpenSearch Dashboards`). I think it's the build folder or file name. Add a property `build.filename` and call the field in `BundleRecorder` `build_filename` to be consistent with `build_id`. See if there are other places we do `name.lower` and replace those too.

2021-12-07 17:01 UTC, dblock commented
> Why isn't the `job-name-opensearch` part of the url sufficiently unique?

If I look at something like `bundle-build` in S3 it's hard to know what that really is I guess. And also think it's good not to rely on the job name in case we move/combine things?

2021-12-07 17:04 UTC, tianleh commented
> Please provide background for this change, its a breaking change to the url schema

This is the bug issue. https://github.com/opensearch-project/opensearch-build/issues/1264

2021-12-07 18:13 UTC, peternied commented
Thanks for the bug link, I would prefer to see is that there is a directory structure on disk and after the build/assembly process that structure is exactly the same as what is uploaded to s3.  With this change it looks like only the s3 pathing is changing but not the local paths, were the local paths already changed - hence this bug?

2021-12-07 19:48 UTC, tianleh commented
> Thanks for the bug link, I would prefer to see is that there is a directory structure on disk and after the build/assembly process that structure is exactly the same as what is uploaded to s3. With this change it looks like only the s3 pathing is changing but not the local paths, were the local paths already changed - hence this bug?

This is how the disk structure:
-builds
  -opensearch
  -opensearch-dashboards
-dist
  -opensearch
  -opensearch-dashboards

This is same as the S3 structure. The current issue is that the location data inside bundle manifest yml is wrong (missing the sub dir). 

The reason why disk bundle is working is that the disk output is updated properly here https://github.com/opensearch-project/opensearch-build/blob/main/src/run_assemble.py#L30

However, the output logic for endpoint is handled separately inside https://github.com/opensearch-project/opensearch-build/blob/c7049633b1f6727f2f8fae7292949ca353b6ae37/src/assemble_workflow/bundle_recorder.py#L47

This reminds me that we may further extend @dblock  's suggestion as follows:
1) add `filename` to `build` manifest so that bundle process no longer needs to worry about inferring such from build name

2) unify the output logic to handle both file and url. https://github.com/opensearch-project/opensearch-build/blob/c7049633b1f6727f2f8fae7292949ca353b6ae37/src/run_assemble.py#L30 Thus base url will be passed into this. Bundle Recorder no longer needs the base_url https://github.com/opensearch-project/opensearch-build/blob/c7049633b1f6727f2f8fae7292949ca353b6ae37/src/assemble_workflow/bundle_recorder.py#L19

2021-12-07 21:52 UTC, peternied commented on src/assemble_workflow/bundle_recorder.py
> +        path = "/".join((folder, self.product, rel_path))
Not sure this is the right place for this change, when the relative path comes in at line 61, shouldn't it match the path from the local file system?

2021-12-07 21:53 UTC, peternied commented on src/assemble_workflow/bundle_recorder.py
> +        path = "/".join((folder, self.product, rel_path))
I would hope making by making the `record(...)` call simpler, it would eliminate the need for additional logic

2021-12-08 09:04 UTC, tianleh commented
Created a separate PR to handle the new attribute in build manifest to reduce potential size of this PR https://github.com/opensearch-project/opensearch-build/pull/1270

2021-12-08 09:10 UTC, tianleh commented on src/assemble_workflow/bundle_recorder.py
> +        path = "/".join((folder, self.product, rel_path))
This change is intended to match the local file system. `self.product` is the sub dir `opensearch` or `opensearch-dashboards`.

Once related PR for `build.filename` https://github.com/opensearch-project/opensearch-build/pull/1270 is merged, I will do some refactoring to make the `record_component` logic simple.

2021-12-08 09:45 UTC, tianleh commented on src/assemble_workflow/bundle_recorder.py
> +        path = "/".join((folder, self.product, rel_path))
The existing code is indeed hard to understand. I have to experiment with many logging statements to fully understand the logic flow. To summarize the confusion points, there are two layers:

1. Disk assemble path logic is handled inside run_assemble https://github.com/opensearch-project/opensearch-build/blob/main/src/run_assemble.py#L28 As a contrast, endpoint assemble path logic is handled inside bundle recorder https://github.com/opensearch-project/opensearch-build/blob/f83f53c7ce7b582b2871cceb1c3a52bc08fad9c5/src/assemble_workflow/bundle_recorder.py#L42
2. Regardless of disk or endpoint assemble, there is always a local disk output saved. Such output could be confusing since both disk and endpoint assemble have it.

I already have a POC in local branch which can encapsulate the complexity mentioned above. Once #1270 is merged, I will eliminate the confusion.

2021-12-08 12:53 UTC, dblock commented on src/assemble_workflow/bundle_recorder.py
> +        path = "/".join((folder, self.product, rel_path))
Great stuff @tianleh !

2021-12-08 20:14 UTC, tianleh commented
Related PR https://github.com/opensearch-project/opensearch-build/pull/1270 has been merged, rebasing this branch first to get latest change.

2021-12-08 20:59 UTC, dblock commented on src/assemble_workflow/bundle_recorder.py
> +        self.product = build.name.lower().replace(" ", "-")
Rename to build_filename and use `build.filename`.

2021-12-08 21:15 UTC, tianleh commented
Introduce a `BundleLocation` to unify the logic for disk and endpoint bundle logic. Verified locally that location information is correctly set in the bundle manifest for both cases.

Send for review on the functional part. Unit test is in progress.

2021-12-08 22:50 UTC, dblock commented
👍

2021-12-08 23:02 UTC, peternied commented
Magnificent!

2021-12-09 00:16 UTC, dblock approved these changes

2021-12-09 00:27 UTC, peternied approved these changes

2021-12-09 00:43 UTC, merged