Updated manifest for 1.2.1 with tags
opensearch-project/opensearch-build pull request #1326
Opened 2021-12-14 14:31 UTC by davidlago

Signed-off-by: Dave Lago <davelago@amazon.com>

### Description
Updated plugin references in the `1.2.1` manifest to point to the `1.2.1.0` tags instead of the `1.2` branches

- [x] OpenSearch 
- [x] common-utils
- [x] job-scheduler
- [x] alerting
- [x] asynchronous-search
- [x] index-management
- [x] k-NN
- [x] security
- [x] performance-analyzer
- [x] anomaly-detection
- [x] cross-cluster-replication
- [x] sql
- [x] dashboards-reports
- [x] opensearch-observability

### Issues Resolved
- Finishes the post release task 'Replace refs in manifests/1.2.1 with tags.' from https://github.com/opensearch-project/opensearch-build/issues/1290
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-12-14 14:32 UTC, dblock approved these changes

2021-12-14 14:32 UTC, dblock commented
Has everyone tagged yet? Can we just do a bulk tags update in 1 PR?

2021-12-14 14:37 UTC, davidlago commented
No. I just checked the first one on the manifest (common-utils) and the last tag there is still `1.2.0.0`

2021-12-14 16:37 UTC, tianleh approved these changes

2021-12-14 16:56 UTC, peternied requested changes
Thanks @davidlago for getting this ball rolling.  If you don't mind I'm going to use this as the focal update to make sure we've updated all of the ref targets to tags.  I've updated the description on the issue.  This way you can get all credit as the first to finish this post release task

If you do mind let me know, and we can break this apart.

2021-12-14 17:18 UTC, dblock commented
For this PR change everything to `tags/...` and CI will keep failing until we're done.

2021-12-14 17:30 UTC, davidlago commented
Done. Assuming everyone's naming convention for tags is such that the tag is `1.2.1.0` except for the core project with `1.2.1`.

2021-12-15 01:06 UTC, gaiksaya commented
Merging this PR as tests have passed now. Thanks @davidlago for the changes.

2021-12-15 01:07 UTC, merged