[Dashboards] check BuildManifest has artifacts
opensearch-project/opensearch-build pull request #1568
Opened 2022-01-27 21:49 UTC by kavilla

### Description
Verifies if the build manifest has artifacts or not before using the value.
This allows for components that don't produce build artifacts to be passed
to the groovy class without failing.

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/1565

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-01-27 21:54 UTC, kavilla commented
Build 27 was with these changes and build 28 is where I temp removed this fix. So this fixes it the issue I was seeing.

![Screen Shot 2022-01-27 at 1 53 18 PM](https://user-images.githubusercontent.com/12060704/151449978-75e16369-d0e0-492b-9925-e770ce346fa7.png)

2022-01-27 22:40 UTC, peternied requested changes

2022-01-27 22:40 UTC, peternied commented on src/jenkins/BuildManifest.groovy
> +            this.artifacts = data.artifacts ? new HashMap<>(data.artifacts) : new HashMap<>()
Could we add a test, or alter one of the existing tests to exercise this functionality?

2022-01-27 23:30 UTC, peternied commented on src/jenkins/BuildManifest.groovy
> +            this.artifacts = data.artifacts ? new HashMap<>(data.artifacts) : new HashMap<>()
Note; I see that you altered the test data, but its not very clear how that alterative prevents the nullpointer, I was hoping you could create a new test that invokes `BuildManifest(...)` with artifacts undefined

2022-01-28 16:00 UTC, peternied approved these changes

2022-01-30 20:58 UTC, dblock approved these changes

2022-01-30 20:58 UTC, merged