Adding 1.2.5 manifest
opensearch-project/opensearch-build pull request #1584
Opened 2022-02-02 22:29 UTC by abhinavGupta16

### Description
Adding manifest files for `1.2.5`
  
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-02-02 22:35 UTC, gaiksaya commented on jenkins/check-for-build.jenkinsfile
>              H/10 * * * * %INPUT_MANIFEST=1.2.4/opensearch-1.2.4.yml;TEST_MANIFEST=1.2.4/opensearch-1.2.4-test.yml;TARGET_JOB_NAME=distribution-build-opensearch
We should remove 1.2.4 from this cron. The version is already out we do not need to keep rebuilding it

2022-02-02 22:35 UTC, gaiksaya commented on manifests/1.2.5/opensearch-1.2.5.yml
> +  - name: common-utils
I do not believe we add all components at first. Most of the components build might fail due to version incompatibility if the version is main is not incremented.

2022-02-02 22:37 UTC, peternied reviewed
We shouldn't merge this, after OpenSearch creates a 1.2.5 branch this manifest will be created automatically via this repos github actions

2022-02-03 00:14 UTC, abhinavGupta16 commented
> We shouldn't merge this, after OpenSearch creates a 1.2.5 branch this manifest will be created automatically via this repos github actions

I'll make this PR a draft

2022-02-03 01:54 UTC, dblock requested changes
This won't work. In order to produce a 1.2.5 successful build there needs to be version increments, then a -SNAPSHOT build with common-utils, then another with job-scheduler, etc. This is an incremental process that is semi-automated, but it runs reliable CI and ensures that we have a working 1.2.5 without ever being broken.

I would just close this without merging.

2022-02-03 19:33 UTC, abhinavGupta16 commented
Closing The PR since this process is automated

2022-02-03 19:33 UTC, closed without merging