Change the issue title for release to be 'proposed'
opensearch-project/opensearch-build pull request #1591
Opened 2022-02-03 18:15 UTC by peternied

The current langauge makes the autocut release tickets seem like a
commitment for a release, whereas they are a best guess effort
that a release could happen.  E.g. there might ne a patch release in
flight and then don't release that in favor of a minor release that
also includes the contents as the patch release.

### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-02-03 18:18 UTC, dblock requested changes
Every open issue is a proposal or a bug or something like that. Not sure who feels that just because we have a ticket open that says "Release v1.2.3" that it's some kind of promise or commitment. Can you please point me to a discussion about that?

I am afraid this will re-auto-cut all old version tickets, see https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/releases.yml#L32, so this implementation doesn't work.

2022-02-03 18:26 UTC, peternied commented
> Can you please point me to a comment where someone is confused about that?

@bbarani can you provide background on this?

> I am afraid this will re-auto-cut all old version tickets

Yes, if updating the title is the right path I could spend more time looking into how we can prevent recuts.  Making an update to the issue creation GHA could be a way.

2022-02-03 18:31 UTC, dblock commented
> Yes, if updating the title is the right path I could spend more time looking into how we can prevent recuts. Making an update to the issue creation GHA could be a way.

FYI I had forked the original GHA given its lack of maintenance, https://github.com/dblock/create-a-github-issue

2022-02-14 15:16 UTC, peternied commented
@bbarani I haven't seen any updates, feel free to reopen this PR or one like it if you feel this change is needed

2022-02-14 15:16 UTC, closed without merging