Remove PA-RCA files from OS home dir
opensearch-project/opensearch-build pull request #1674
Opened 2022-02-25 23:31 UTC by kjoseph07

Signed-off-by: Karishma Joseph <karisjos@amazon.com>

[Merge only when PA is stable]

### Description
Remove the`<OS_HOME>/performance-analyzer-rca` folder from the OS home directory. This way there is only one location for PA plugin and PA-RCA process: `<OS_HOME>/plugins/opensearch-performance-analyzer`. 

Contents of `<OS_HOME>/performance-analyzer-rca` before:
```
bin  lib  pa_bin  pa_config
```

`pa_bin` and `pa_config` in `<OS_HOME>/performance-analyzer-rca` and `<OS_HOME>/plugins/opensearch-performance-analyzer` were exactly the same. Hence, no action needs to be taken for these two folders.

Copy `bin` into `<OS_HOME>/plugins/opensearch-performance-analyzer` and rename as `rca_bin`.

Copy `lib` into `<OS_HOME>/plugins/opensearch-performance-analyzer` and rename as `rca_lib`. Remove all the common library files between `<OS_HOME>/plugins/opensearch-performance-analyzer` and `<OS_HOME>/plugins/opensearch-performance-analyzer/rca_lib` so as to reduce the memory footprint.
 
### Issues Resolved
https://github.com/opensearch-project/performance-analyzer/issues/82
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-02-28 22:49 UTC, dblock commented
This feels odd, shouldn't the plugins be publishing only the things they need vs. install scripts removing dups?

Next, this is the default script. I think we need to do different things for different versions, so maybe it's time to absorb these in the PA repo?

2022-03-08 20:53 UTC, gaiksaya commented
Hi @kjoseph07 is this change intended for 1.3.0? Is yes we need to address and merge this before before the build is finalized.
Thanks!

2022-04-06 00:40 UTC, sruti1312 approved these changes

2022-04-06 14:00 UTC, dblock approved these changes

2022-04-06 14:01 UTC, dblock requested changes
See my question above, https://github.com/opensearch-project/opensearch-build/pull/1674#issuecomment-1054756192

2022-07-13 20:20 UTC, bbarani commented
@kjoseph07 @sruti1312 Can you please address the above comment?

2022-10-18 20:12 UTC, bbarani commented
@kjoseph07 @sruti1312 @opensearch-project/performance-analyzer Can you please provide update?

2022-12-05 19:55 UTC, bbarani commented
@opensearch-project/performance-analyzer @sruti1312 Can you please provide an update?

2022-12-06 20:53 UTC, kkhatua commented
@bbarani  We need to re-test this before merge. We'll try to pick this up and verify + merge by end of the month.

@dblock  we're in this situation because the dedup is for the side-car process -- RCA . Duplication was done to keep the development & build independent and fast, but at the cost of disk space (which is cheap). As this is only a resource (disk) optimization, it hasn't been high priority as compared to other items, such as CVEs.

2023-01-30 06:40 UTC, bbarani commented
https://github.com/orgs/opensearch-project/teams/performance-analyzer @sruti1312 @kaushalmahi12
Can you please provide an update?

2023-03-15 21:05 UTC, kkhatua commented
Tagging @praveensameneni to mark this in their backlog.

2023-07-28 20:58 UTC, bbarani commented
@praveensameneni @kkhatua I will be closing this PR in 7 days if we are not getting any traction.

2023-08-22 21:21 UTC, gaiksaya commented
Closing this as a stale PR! Please re-open with updated changes if you wish to contribute.
Thanks!

2023-08-22 21:21 UTC, closed without merging