Add performance and longevity testing validation to the release template
opensearch-project/opensearch-build pull request #1752
Opened 2022-03-14 18:00 UTC by travisbenedict

Signed-off-by: Travis Benedict <benedtra@amazon.com>

### Description
Add steps to the release template for validating performance and longevity test results. These steps are not necessarily exhaustive but can serve as a starting point for our release process. Ultimately, these validations should be automated as our performance testing automation is built out more. 

More details on the testing setup can be found in this issue outlining the results of performance experiments that I conducted - https://github.com/opensearch-project/OpenSearch/issues/2461
 
### Issues Resolved

 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-03-16 14:55 UTC, dblock requested changes

2022-03-16 14:55 UTC, dblock commented on src/test_workflow/README.md
> +#### How to identify regressions in performance tests
Add to TOC, cleanup capitalization to match other topics.

I would rename to "Identifying Regressions in Performance Tests"

2022-03-16 14:55 UTC, dblock commented on src/test_workflow/README.md
> +Additionally, error rates on the order of 0.01% are acceptable, though higher ones may be cause for concern.
This should be a section of its own. What happens if the error rates are higher? What does one do?

2022-03-16 14:55 UTC, dblock commented on src/test_workflow/README.md
> +#### How to identify issues in longevity tests
There's zero information on what longevity tests are anywhere in these docs. To an uneducated reader it's impossible to understand what one does with it. Please provide context to all these things.

2022-03-16 19:08 UTC, travisbenedict commented on src/test_workflow/README.md
> +The values listed below are **not** applicable to other configurations. More details on the test setup can be found here: https://github.com/opensearch-project/OpenSearch/issues/2461
Good points. I'll rewrite this section

2022-03-16 20:59 UTC, travisbenedict commented on src/test_workflow/README.md
> +    - [Test Workflow (in development)](#test-workflow-in-development)
These got reformatted by my IDE. Will move them back

2022-03-17 16:44 UTC, travisbenedict commented on src/test_workflow/README.md
> +Performance tests from `test.sh` are executed using an internal service which automatically provisions hosts that run [OpenSearch Benchmark](https://github.com/opensearch-project/OpenSearch-Benchmark
I like that a lot better. Thanks!

2022-03-17 17:24 UTC, merged

2022-03-17 17:27 UTC, travisbenedict commented
Thanks for the help on this @dblock. I really appreciate the feedback