lower freq for build for 1.3.1 opensearch-dashboards
opensearch-project/opensearch-build pull request #1941
Opened 2022-04-08 00:46 UTC by abhinavGupta16

Signed-off-by: Abhinav Gupta <abhng@amazon.com>

### Description
Lower build freq for release versions
 
### Issues Resolved
Post release activity - #1885 

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-08 00:48 UTC, zelinh approved these changes

2022-04-08 00:53 UTC, peterzhuamazon requested changes
No need to rebuild just remove it.
Same for 1.2.x

2022-04-08 01:15 UTC, abhinavGupta16 commented
> No need to rebuild just remove it. Same for 1.2.x

I have remove it. Although, how do we decide which ones to keep and which ones to remove?

2022-04-08 19:49 UTC, kavilla approved these changes

2022-04-12 21:33 UTC, peterzhuamazon approved these changes

2022-04-12 21:33 UTC, merged