update release issue with steps to update ansible and helm
opensearch-project/opensearch-build pull request #1942
Opened 2022-04-08 00:55 UTC by abhinavGupta16

Signed-off-by: Abhinav Gupta <abhng@amazon.com>

### Description
Update release issue to include steps for updating Ansible and Helm
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-08 00:59 UTC, peterzhuamazon commented on .github/ISSUE_TEMPLATE/release_template.md
> +- [ ] Increment [version for Ansible Charts](https://github.com/opensearch-project/ansible-playbook/pull/50) for the `{{ env.VERSION }}` release
Please state these are samples prs.

2022-04-08 20:50 UTC, dblock requested changes

2022-04-08 20:50 UTC, dblock commented on .github/ISSUE_TEMPLATE/release_template.md
> +- [ ] Increment version for Ansible Charts [(sample PR)](https://github.com/opensearch-project/ansible-playbook/pull/50) for the `{{ env.VERSION }}` release
Both sentences missing periods.

2022-04-11 20:49 UTC, abhinavGupta16 commented on .github/ISSUE_TEMPLATE/release_template.md
> +- [ ] Increment version for Ansible Charts [(sample PR)](https://github.com/opensearch-project/ansible-playbook/pull/50) for the `{{ env.VERSION }}` release
updated

2022-04-11 23:04 UTC, dblock approved these changes

2022-04-11 23:04 UTC, merged