Update README with instructions for assembly.
opensearch-project/opensearch-build pull request #199
Opened 2021-08-12 18:50 UTC by mch2

Signed-off-by: Marc Handalian <handalm@amazon.com>

### Description
Update README with instructions for assembly.
 
### Issues Resolved
README update only
 
### Check List
- [ x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-08-12 19:22 UTC, dblock requested changes

2021-08-12 19:22 UTC, dblock commented on bundle-workflow/README.md
> +Bundling step:
Bundle Step:

to be consistent

2021-08-12 19:22 UTC, dblock commented on bundle-workflow/README.md
> +./bundle-workflow/assemble.sh /path/to/build/manifest
Maybe change this to the actual manifest that’s output by the above?

2021-08-12 20:58 UTC, dblock approved these changes

2021-08-13 17:33 UTC, camerski approved these changes

2021-08-13 17:43 UTC, peternied approved these changes

2021-08-13 18:07 UTC, merged