Fix incorrect path in documentation
opensearch-project/opensearch-build pull request #2092
Opened 2022-05-05 18:56 UTC by peternied

### Description
When I was authoring https://github.com/opensearch-project/security/pull/1811 I had to iterate a couple of extra times and debug the python code because the custom script was not being picked up due to the incorrect path.  

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-05-05 20:27 UTC, dblock requested changes
I believe we support both `scripts/build.sh` and `build.sh`, but should really standardize on one. I'd prefer we correct this to `scripts/build.sh`, and have a separate ticket to get rid of anything at root.

2022-05-05 22:04 UTC, peternied commented
> I believe we support both scripts/build.sh and build.sh, but should really standardize on one.

I'm in favor of `scripts/build.sh`, updated the documentation.

> have a separate ticket to get rid of anything at root.

Would you want to go into previously shipped release branches and fix this?  IMO, I'd rather keep the code supporting both methods, but shift the documentation to get folks pointed towards `scripts/build.sh` which seems more correct.

2022-05-06 16:47 UTC, dblock commented
> Would you want to go into previously shipped release branches and fix this? IMO, I'd rather keep the code supporting both methods, but shift the documentation to get folks pointed towards `scripts/build.sh` which seems more correct.

I wouldn't want to change code in previous releases. I think the build.sh location at root could be deprecated with a warning.

2022-05-06 16:47 UTC, dblock approved these changes

2022-05-06 16:47 UTC, merged