Added alerting and ISM to the back and frontend 2.2 manifests.
opensearch-project/opensearch-build pull request #2427
Opened 2022-08-05 15:30 UTC by AWSHurneyt

### Description
Added alerting and ISM to the back and frontend 2.2 manifests.

### Issues Resolved
https://github.com/opensearch-project/alerting/issues/498
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/293
https://github.com/opensearch-project/index-management/issues/431
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/217

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-05 22:05 UTC, peterzhuamazon commented on manifests/2.2.0/opensearch-2.2.0.yml
> +        - gradle:properties:version
You are failing because your indentation is not correct.

2022-08-05 23:20 UTC, peterzhuamazon approved these changes

2022-08-05 23:21 UTC, zelinh approved these changes

2022-08-05 23:28 UTC, peterzhuamazon requested changes
Block until IM is back to the manifests.
Waiting for:
https://github.com/opensearch-project/index-management/pull/446
https://github.com/opensearch-project/index-management/pull/447

2022-08-05 23:50 UTC, AWSHurneyt commented
> Block until IM is back to the manifests. Waiting for: [opensearch-project/index-management#446](https://github.com/opensearch-project/index-management/pull/446) [opensearch-project/index-management#447](https://github.com/opensearch-project/index-management/pull/447)

ISM 2.2 branches have been cut, and added back to the manifests in this PR.

2022-08-06 00:13 UTC, peterzhuamazon approved these changes

2022-08-06 01:17 UTC, merged