Added notifications plugin to 2.3 manifest files.
opensearch-project/opensearch-build pull request #2551
Opened 2022-09-02 21:41 UTC by AWSHurneyt

Signed-off-by: AWSHurneyt <hurneyt@amazon.com>

### Description
Added notifications plugin to 2.3 manifest files.

### Issues Resolved
https://github.com/opensearch-project/notifications/issues/516

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-07 17:31 UTC, AWSHurneyt commented
I'll revise this PR once the 2.3 branch is cut for the notifications plugin.

2022-09-07 17:50 UTC, AWSHurneyt commented
> Hey @AWSHurneyt can you please resolve the conflict as well.

Will do. I'll fix the merge conflict when I adjust the `ref` to the 2.3 branch.

2022-09-08 00:21 UTC, gaiksaya commented
@AWSHurneyt Pleas fix merge-conflicts too. Thanks!

2022-09-08 03:07 UTC, gaiksaya requested changes

2022-09-08 03:07 UTC, gaiksaya commented on manifests/2.3.0/opensearch-2.3.0.yml
> +- name: notifications-core
Need to fix the Indentation error

2022-09-08 15:26 UTC, AWSHurneyt commented
Closing in favor of https://github.com/opensearch-project/opensearch-build/pull/2581

2022-09-08 15:26 UTC, closed without merging