Add sec
opensearch-project/opensearch-build pull request #2670
Opened 2022-09-28 19:12 UTC by zelinh

### Description
Add security plugin into the manifest

### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/2650

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-28 19:56 UTC, peterzhuamazon requested changes
Please create a better title for the PR with appropriate details.

2022-09-28 21:29 UTC, zelinh commented
> Please create a better title for the PR with appropriate details.

Sorry seems like i forgot to change the PR title so it takes from the commit message :D

2022-09-29 23:22 UTC, peterzhuamazon approved these changes

2022-09-29 23:22 UTC, merged

2022-09-29 23:22 UTC, peterzhuamazon commented
Merge this as the groovy failure is not related. Still debugging.