Add replication plugin to Opensearch 1.1 build manifest
opensearch-project/opensearch-build pull request #315
Opened 2021-08-25 11:17 UTC by ankitkala

### Description
Add replication plugin to Opensearch 1.1 build manifest
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/266

### Testing done
`./bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --snapshot --component cross-cluster-replication`
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-08-25 13:04 UTC, dblock approved these changes
Just to double-confirm, what does the .zip file name/output look like from both `--snapshot` and without run?

2021-08-31 18:29 UTC, dblock commented
I don't see a CI on https://github.com/opensearch-project/cross-cluster-replication. Because we're rebuilding the world in bundle-workflow we can't add a repo without that or this repo will effectively become the CI for cross-cluster-replication.

2021-08-31 18:30 UTC, dblock requested changes
cross-cluster-replication will need CI

2021-09-06 06:51 UTC, ankitkala commented
> I don't see a CI on https://github.com/opensearch-project/cross-cluster-replication. Because we're rebuilding the world in bundle-workflow we can't add a repo without that or this repo will effectively become the CI for cross-cluster-replication.

These are separate set of changes which are being added here: https://github.com/opensearch-project/cross-cluster-replication/pull/123

2021-09-16 14:28 UTC, peternied submitted a review, later dismissed
@ankitkala The new CI check is not yet [passing](https://github.com/opensearch-project/cross-cluster-replication/commits/main), please resolve these issues and ping us to take another look.

2021-09-27 18:20 UTC, saikaranam-amazon commented
@peternied Could you please take a look into the PR?
- Build issues are resolved

2021-09-27 19:20 UTC, peterzhuamazon approved these changes

2021-09-27 19:22 UTC, gaiksaya commented on manifests/1.1.0/opensearch-1.1.0.yml
> +    ref: 1.1
Needs to be a string

2021-09-27 19:39 UTC, saikaranam-amazon commented on manifests/1.1.0/opensearch-1.1.0.yml
> +    ref: 1.1
Done

2021-09-27 19:51 UTC, gaiksaya approved these changes

2021-09-27 19:54 UTC, dblock commented
More tests failing.

2021-09-27 20:12 UTC, dblock approved these changes

2021-09-27 20:30 UTC, gaiksaya approved these changes

2021-09-27 20:38 UTC, peterzhuamazon approved these changes

2021-09-27 20:58 UTC, merged