Add Jenkins Job for Validation workflow
opensearch-project/opensearch-build pull request #3555
Opened 2023-05-24 21:23 UTC by Divyaasm

### Description

Created jenkins Job for Validation Workflow

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-05-25 18:47 UTC, gaiksaya requested changes

2023-05-25 18:47 UTC, gaiksaya commented on jenkins/validate-artifacts/validate-artifacts.jenkinsfile
> +            description: 'Enter the OpenSearch and OpenSearch Dashboards VERSION that needs to be validated',
```suggestion
            description: 'Enter the OpenSearch and OpenSearch Dashboards version that needs to be validated',
```

2023-05-25 18:47 UTC, gaiksaya commented on jenkins/validate-artifacts/validate-artifacts.jenkinsfile
> +            description: 'Enter the distribution type among [tar,rpm,yum,docker] default is set to All distributions',
```suggestion
            description: 'Enter the distribution type among tar, rpm, yum, docker separated by space. Defaults to "tar rpm yum docker"',
```

2023-05-25 18:47 UTC, gaiksaya commented on jenkins/validate-artifacts/validate-artifacts.jenkinsfile
> +            description: 'Enter the architecture type among x64 and arm64 default is set to [x64,arm64]',
```suggestion
            description: 'Enter the architecture type among x64 and arm64 separated by space. Defaults "x64,arm64"',
```

2023-05-25 18:47 UTC, gaiksaya commented on jenkins/validate-artifacts/validate-artifacts.jenkinsfile
> +            description: 'Enter the build number for opensearch - This parameter is applicable only for Docker Validation',
```suggestion
            description: 'Enter the build number for OpenSearch - This parameter is applicable only for Docker Validation',
```

2023-05-25 18:47 UTC, gaiksaya commented on jenkins/validate-artifacts/validate-artifacts.jenkinsfile
> +            description: 'Enter the build number for opensearch Dashboards - This parameter is applicable only for Docker Validation',
```suggestion
            description: 'Enter the build number for OpenSearch Dashboards - This parameter is applicable only for Docker Validation',
```

2023-05-25 18:47 UTC, gaiksaya commented on jenkins/validate-artifacts/validate-artifacts.jenkinsfile
> +            description: 'Choose among validate-digest-only or using-staging-artifact-only [Optional]',
```suggestion
            description: 'Optional args for docker validation. Currently supports validate-digest-only or using-staging-artifact-only. Defaults to using-staging-artifact-only',
```

2023-05-25 18:47 UTC, gaiksaya commented on jenkins/validate-artifacts/validate-artifacts.jenkinsfile
> +                        error("Provide OS_BUILD_NUMBER and OSD_BUILD_NUMBER for Docker Validation")
```suggestion
                        error("Provide OS_BUILD_NUMBER and OSD_BUILD_NUMBER args for Docker Validation")
```

2023-05-25 18:47 UTC, gaiksaya commented on jenkins/validate-artifacts/validate-artifacts.jenkinsfile
> +                        error('Provide version number for the artifacts')
```suggestion
                        error('VERSION cannot be empty. Please provide version of the artifacts to validate')
```

2023-05-25 18:47 UTC, gaiksaya commented on tests/jenkins/TestValidateArtifacts.groovy
> +
Add one more test to throw an error in case docker args are not provided.

2023-06-08 18:17 UTC, gaiksaya approved these changes

2023-06-08 23:53 UTC, prudhvigodithi commented
Hey @Divyaasm can you please take of the NIT's, we can proceed to merge this PR.
Thank you

2023-06-09 00:06 UTC, gaiksaya commented
I think we are good @prudhvigodithi The nits are showing as `outdated`

2023-06-09 20:05 UTC, merged