Add common-utils and job-scheduler components to 2.11.1 OS manifest
opensearch-project/opensearch-build pull request #4187
Opened 2023-10-31 17:52 UTC by Divyaasm

### Description
Add js and cu to 2.11.1
### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-31 20:03 UTC, zelinh approved these changes

2023-10-31 20:05 UTC, gaiksaya commented
You can add components at once, once they are ready. 2.x line has own maven snapshot publication workflow so no blockers.

2023-11-14 18:57 UTC, gaiksaya requested changes
Please fix linting issue and PR description along with the title. Thanks!

2023-11-14 19:11 UTC, gaiksaya approved these changes

2023-11-14 19:24 UTC, merged