Onboarding skills repo
opensearch-project/opensearch-build pull request #4387
Opened 2024-01-30 02:10 UTC by zane-neo

### Description
Onboarding skills repo

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/4378

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-01-30 18:07 UTC, peterzhuamazon requested changes

2024-01-30 18:07 UTC, peterzhuamazon commented on manifests/2.12.0/opensearch-2.12.0.yml
> +      - gradle:dependencies:opensearch.version
Please remove this as we dont need this section anymore.

2024-01-30 18:07 UTC, peterzhuamazon commented on manifests/2.12.0/opensearch-2.12.0-concurrent-search-test.yml
> +  - name: skills
Please add a newline before this, and confirm is skills GA or experimental?

2024-01-30 18:22 UTC, peterzhuamazon commented
We also need to wait for a bit before merging, as skills repo has wrong rootname, wrong m2 folder, and others.
Zan is working to fix those.

2024-01-31 21:43 UTC, prudhvigodithi approved these changes

2024-01-31 21:43 UTC, peterzhuamazon approved these changes
Thanks @zane-neo.

I also tweaked a few issues I see in the workflow ymls, and resolve conflicts.

Will ask @prudhvigodithi to give another approval. Thanks.

2024-01-31 22:11 UTC, merged

2024-02-06 18:30 UTC, prudhvigodithi commented
Hey @zane-neo can you please take care of this issue https://github.com/opensearch-project/skills/issues/188#issue-2121422972 ?
Thank you