Add publishGradleCheckTestResults lib to gradle-check
opensearch-project/opensearch-build pull request #4559
Opened 2024-03-22 18:51 UTC by rishabh6788

### Description
This PR adds gradle-check test results publishing script to post stage. See https://github.com/opensearch-project/opensearch-build-libraries/pull/397 for more details.

### Issues Resolved
#4469 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-22 18:52 UTC, gaiksaya requested changes
Please get this change after 2.13.0 as actively changes are being merged and we do not want to block the release process.

2024-03-22 18:56 UTC, rishabh6788 commented
This will not block the release process, tested on Ubuntu host and it is working as expected.

2024-03-22 18:59 UTC, peterzhuamazon approved these changes

2024-03-25 21:54 UTC, gaiksaya approved these changes
Unblocking since we have RC2 and need to monitor gradle flaky tests

2024-03-25 21:55 UTC, merged