URL encode test result files
opensearch-project/opensearch-build pull request #4574
Opened 2024-03-26 16:22 UTC by Swiddis

### Description
Following up on #4569: escape the filenames in the test manifest file to better support tools scanning these files for links.

### Issues Resolved
Closes #4569.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-27 00:11 UTC, zelinh reviewed
Thanks for the PR @Swiddis.
I am aware of this issue and this might cause confusion; but I believe the link should be accessible if you include all of the URL address with spaces.

One thing I'm worried about this PR is that our implementation should also be compatible with local directory address when we pass in local `base_path` so replacing space here may not be working for local test record.

2024-03-27 18:03 UTC, Swiddis commented
Hm, good point on local test suites... I could try introducing a check for if `base_path` starts with `http(s)://` if that would suffice? Or maybe more generally `[scheme]://`.

I'm aware that the link is accessible if you copy the address with spaces -- it's mostly annoying with some text editors when copying directly from yaml, since they typically won't respect the yaml unquoted-string whitespace conventions and this ends up in needing to find and delete stray spaces.

2024-03-27 21:38 UTC, zelinh commented
> Hm, good point on local test suites... I could try introducing a check for if `base_path` starts with `http(s)://` if that would suffice? Or maybe more generally `[scheme]://`.
> 
> I'm aware that the link is accessible if you copy the address with spaces -- it's mostly annoying with some text editors when copying directly from yaml, since they typically won't respect the yaml unquoted-string whitespace conventions and this ends up in needing to find and delete stray spaces.

Yeah I think you could have another check to see if `base_path` starts with `https://` as what we did here. https://github.com/opensearch-project/opensearch-build/blob/b86cf756be5df4f32d73753bf45c12377792e234/src/test_workflow/test_recorder/test_recorder.py#L40-L44

2024-03-27 22:52 UTC, Swiddis commented
Updated the logic and associated test cases

2024-03-28 16:27 UTC, peterzhuamazon requested changes
Does it make sense to change on line 40 instead?

2024-03-28 16:32 UTC, peterzhuamazon commented
> Does it make sense to change on line 40 instead?
> 
> https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/test_recorder/test_recorder.py#L40

Ignore it, I think I didnt realize the `file` value is appended later on.

2024-03-28 16:33 UTC, peterzhuamazon approved these changes

2024-03-28 16:33 UTC, peterzhuamazon commented
Thanks.

2024-03-28 23:04 UTC, zelinh commented on tests/tests_test_workflow/test_recorder/test_test_recorder.py
> +        self.assertEqual(file_path, [os.path.join("https://working-directory", "sub-directory", "A+long+test+case+name")])
For this case, I think we should just join them with `/` instead of `os.path.join`.

2024-04-01 20:12 UTC, zelinh approved these changes
LGTM! Thanks.

2024-04-01 20:16 UTC, merged