Add 1.1.0 releasenotes draft md file
opensearch-project/opensearch-build pull request #478
Opened 2021-09-14 19:28 UTC by peterzhuamazon

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add 1.1.0 releasenotes draft md file
 
### Issues Resolved
#477
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-09-27 17:03 UTC, stockholmux requested changes
Seems like a lot - mostly repetitive (search/replace, etc.)

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch
Open**S**earch

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Perftop
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch SQL
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Trace Analytics
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection Dashboards
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Cross Cluster Replication
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Notebooks
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Visualizations
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management Dashboards Plugin
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch
Open**S**earch

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting Dashboards Plugin
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Notebooks
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Visualizations
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management Dashboards Plugin
Either Open**S**earch or drop "OpenSearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch
Open**S**earch

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
Either Open**S**earch or drop "Opensearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Perftop
Either Open**S**earch or drop "Opensearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Security
Either Open**S**earch or drop "Opensearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Security Dashboards Plugin
Either Open**S**earch or drop "Opensearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Trace Analytics
Either Open**S**earch or drop "Opensearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
Either Open**S**earch or drop "Opensearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
Either Open**S**earch or drop "Opensearch"

2021-09-27 17:03 UTC, stockholmux commented on release-notes/opensearch-release-notes-1.1.0.md
> +- Pause and Resume API (#10)
Weirdly these aren't links

2021-09-27 18:03 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +OpenSearch and OpenSearch-Dashboards 1.1.0 includes the following features, enhancements, bug fixes, infrastructure, documentation, maintenance, and refactoring updates.
fixed.

2021-09-27 18:03 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
fixed.

2021-09-27 18:03 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting Dashboards Plugin
fixed.

2021-09-27 18:03 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection Dashboards
fxied.

2021-09-27 18:03 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Cross Cluster Replication
fxied.

2021-09-27 18:06 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management Dashboards Plugin
fixed.

2021-09-27 18:06 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
fixed.

2021-09-27 18:06 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection
fixed.

2021-09-27 18:06 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection Dashboards
fixed.

2021-09-27 18:06 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting Dashboards Plugin
fixed.

2021-09-27 18:07 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection
fixed.

2021-09-27 18:07 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Notebooks
fixed.

2021-09-27 18:07 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management
fixed.

2021-09-27 18:07 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
fixed.

2021-09-27 18:08 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Security
fixed.

2021-09-27 18:08 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
fixed.

2021-09-27 18:08 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection
fixed.

2021-09-27 18:08 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection Dashboards
fixed.

2021-09-27 18:08 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Asynchronous Search
fixed.

2021-09-27 18:08 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Asynchronous Search
fixed.

2021-09-27 18:08 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Cross Cluster Replication
fixed.

2021-09-27 18:08 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Reports
fixed.

2021-09-27 18:25 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management Dashboards Plugin
fixed.

2021-09-27 18:25 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Knn
fixed.

2021-09-27 18:25 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch SQL
fixed.

2021-09-27 18:26 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
fixed.

2021-09-27 18:26 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
fixed.

2021-09-27 18:33 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection
fixed.

2021-09-27 18:33 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Asynchronous Search
fixed.

2021-09-27 18:33 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection Dashboards
fixed.

2021-09-27 18:33 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Cross Cluster Replication
fixed.

2021-09-27 18:33 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Reports
fixed.

2021-09-27 18:33 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Notebooks
fixed.

2021-09-27 18:33 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Reports
fixed.

2021-09-27 18:34 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Reports
fixed.

2021-09-27 18:34 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Reports
fixed.

2021-09-27 18:34 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Visualizations
fixed.

2021-09-27 18:34 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management
fixed.

2021-09-27 18:34 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Knn
fixed.

2021-09-27 18:34 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch
fixed.

2021-09-27 18:34 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Perftop
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch SQL
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Trace Analytics
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection Dashboards
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Cross Cluster Replication
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Notebooks
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Visualizations
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management Dashboards Plugin
fixed.

2021-09-27 18:35 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch
fixed.

2021-09-27 18:36 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
fixed.

2021-09-27 18:36 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
fixed.

2021-09-27 18:36 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting Dashboards Plugin
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Notebooks
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Dashboards Visualizations
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management Dashboards Plugin
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Perftop
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Security
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Security Dashboards Plugin
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Trace Analytics
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting
fixed.

2021-09-27 18:38 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Performance Analyzer
fixed.

2021-09-27 18:39 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +- Pause and Resume API (#10)
fixed.

2021-09-27 18:47 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Alerting Dashboards Plugin
fixed.

2021-09-27 18:50 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +* Fix BWC for custom \## ENHANCEMENTS
fixed.

2021-09-27 18:50 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Anomaly Detection Dashboards simple filters ([#68](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/68))
fixed.

2021-09-27 18:50 UTC, peterzhuamazon commented on release-notes/opensearch-release-notes-1.1.0.md
> +### Opensearch Index Management
fixed.

2021-09-27 18:50 UTC, peterzhuamazon commented
I have fixed all issues pointed out by @stockholmux please check again.

2021-09-29 13:26 UTC, stockholmux approved these changes
LGTM

2021-10-01 14:02 UTC, elfisher approved these changes

2021-10-05 22:17 UTC, peternied approved these changes

2021-10-05 22:19 UTC, bbarani approved these changes

2021-10-05 22:19 UTC, merged