Skipping integTest for rpm and deb distribution for CCR
opensearch-project/opensearch-build pull request #4905
Opened 2024-08-02 17:39 UTC by nandnkum

Skipping integTest for cross-cluster-replication component when running on deb and rpm distribution.

2024-08-02 17:48 UTC, peterzhuamazon requested changes
Hi @nandnkum ,

Add some comments.

Once you resolve those I will check if we need test cases update. Thanks.

2024-08-02 17:48 UTC, peterzhuamazon commented on jenkins/opensearch/integ-test.jenkinsfile
> +                    // Skipping integTest for cross-cluster-replication component when running on deb and rpm distribution
Spacing.

2024-08-02 17:48 UTC, peterzhuamazon commented on jenkins/opensearch/integ-test.jenkinsfile
> +                    // Skipping integTest for cross-cluster-replication component when running on deb and rpm distribution
Please also add `TODO` to this comment and link the corresponding issue.
Eventually we would need to fix this as this change is temporary.

Thanks.

2024-08-02 17:48 UTC, peterzhuamazon commented on jenkins/opensearch/integ-test.jenkinsfile
> +                        if ((distribution.equals('rpm') || distribution.equals('deb')) && component_check == 'cross-cluster-replication') {
Can we keep consistent on using `equals` vs `==`.

2024-08-02 18:43 UTC, peterzhuamazon approved these changes
Thanks @nandnkum .

cc: @prudhvigodithi whether we need to merge this next week after 2.16.0 is out. (convert back to draft just in case)

Or we can test earlier on this. Thanks.

2024-08-02 18:45 UTC, gaiksaya commented
Please wait until 2.16.0 is out. If the pipeline breaks due to syntax, release process might be stuck.
Thanks!

Also @nandnkum Is there no plan to support CCR on these distributions long term?

2024-08-02 19:06 UTC, nisgoel-amazon commented
>Also @nandnkum Is there no plan to support CCR on these distributions in the long term?

@gaiksaya for now we don't have any plan to fix these tests on deb/rpm. we need support from release infra team to help over here to create multiple cluster on same ec2.

2024-08-02 19:09 UTC, gaiksaya commented
> > Also @nandnkum Is there no plan to support CCR on these distributions in the long term?
> 
> @gaiksaya for now we don't have any plan to fix these tests on deb/rpm. we need support from release infra team to help over here to create multiple cluster on same ec2.

I see! Trying to think of a better way to skip for specific use-cases (like this one) instead of adding conditional statements. @peterzhuamazon @prudhvigodithi Do you think we can add something in test-manifest to handle this?
We can create an issue and discuss there too.

2024-08-02 19:41 UTC, peterzhuamazon commented
> > > Also @nandnkum Is there no plan to support CCR on these distributions in the long term?
> > 
> > 
> > @gaiksaya for now we don't have any plan to fix these tests on deb/rpm. we need support from release infra team to help over here to create multiple cluster on same ec2.
> 
> I see! Trying to think of a better way to skip for specific use-cases (like this one) instead of adding conditional statements. @peterzhuamazon @prudhvigodithi Do you think we can add something in test-manifest to handle this? We can create an issue and discuss there too.

We can, but that would take significantly time.
For now I am ok to add this condition as we already added a TODO section to fix later.
We can always add improvements later. Thanks.

2024-08-02 19:59 UTC, nisgoel-amazon approved these changes

2024-08-08 19:00 UTC, merged

2024-08-08 19:38 UTC, peterzhuamazon commented
Able to skip, tho not perfect, we should look into directly making the call in python code later.
https://build.ci.opensearch.org/job/integ-test/8532/console

Thanks.