Updates for release documentation around 1.2
opensearch-project/opensearch-build pull request #760
Opened 2021-10-18 20:21 UTC by peternied

### Description
Update release template based on initial changes for the 1.2 release

See the release issue at https://github.com/opensearch-project/opensearch-build/issues/567

### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-10-18 21:45 UTC, peternied commented on .github/ISSUE_TEMPLATE/release_template.md
> +_OpenSearch wide initiatives to improve quailty and consistancy_
🔥 🚑  I'm off to the burn ward!

2021-10-18 23:46 UTC, dblock requested changes
Couple more?

2021-10-18 23:46 UTC, dblock commented on .github/ISSUE_TEMPLATE/release_template.md
> +__Section for links to all component tracking issues__
Nit: this is `__` vs. Campaigns is `_`, let's pick one?

2021-10-18 23:46 UTC, dblock commented on .github/ISSUE_TEMPLATE/release_template.md
> +- [ ] Sanity Testing (RELEASE-minus-8-days - RELEASE-minus-6-days): Sanity testing *and* fixing of any issues found by teams.
any *critical* issues?

2021-10-18 23:46 UTC, dblock commented on .github/ISSUE_TEMPLATE/release_template.md
> +- [ ] Code Complete (RELEASE-minus-14-days - RELEASE-minus-11-days): Teams test their component within the distribution, ensuring integration, backwards compatibility and perf tests pass.
oxford comma?

2021-10-18 23:46 UTC, dblock commented on .github/ISSUE_TEMPLATE/release_template.md
> +_OpenSearch wide initiatives to improve quality and consistency._
Add a space above for consistency with other sections.

2021-10-18 23:46 UTC, dblock commented on README.md
> +The build order first pulls down `OpenSearch-Dashboards` and then utilizes it to build other components. Currently, building plugins requires having the core repository built first to bootstrap and b
🤦  this is me

2021-10-19 18:06 UTC, dblock commented on .github/ISSUE_TEMPLATE/release_template.md
> +__Replace with links to all component tracking issues__
You're still missing a period! ;)

2021-10-19 18:43 UTC, merged