Switching to multi-JDK image, enriching build manifest with desired JDK version
opensearch-project/opensearch-build pull request #769
Opened 2021-10-20 14:43 UTC by reta

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Use new CI Docker images, enriching build manifest with desired JDK version. The build manifest has been enriched with new **optional** section `ci`:

```
ci:
  image:
     name: "opensearchstaging/ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211019"
     args: "-e JAVA_HOME=/opt/java/openjdk-11"
build:
  name: OpenSearch
  version: 2.0.0
```

This build manifest is being read in preparation to running Jenkins job and the its JDK version, if specified, is enforced (the defaults stay unchanged and use JDK-14). 
 
### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/732
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-10-20 16:50 UTC, dblock requested changes
I think it's alright, but I wonder whether we can get closer to what GHA does? 
```
ci:
  image:
     - multi-whatever-docker-container-thing
  env:
     - JAVA_HOME=...
```
Putting those in the manifest would make Jenkinsfile a lot lighter. The environment should be loaded and set when executing the build.

2021-10-20 19:18 UTC, dblock commented
> I would +1 following GHA idioms. But I am completely lost in Python, it goes way beyond my expertise, @peterzhuamazon could you give me a hand here? I can definitely implement the `image` support in manifest but will drown in `dependencies` + build environment manipulation.

I'd be happy to help. Try getting the image going and I can take care of dependences on top of that?
 
> @dblock thank you, I was looking also into `https://github.com/opensearch-project/OpenSearch/blob/main/Jenkinsfile` and it seems like it uses predefined agents `search-cloud-ec2-c518xlarge`, which we have to rebuild out of new images, any hints / people who could help with that?

@peternied @peterzhuamazon ?

2021-10-20 20:09 UTC, dblock commented on jenkins/opensearch/Jenkinsfile
> +                    if (dockerImage == null || dockerImage == "null") {
Let's hard fail here and require the image in CI?

2021-10-20 21:50 UTC, peterzhuamazon commented
> > I would +1 following GHA idioms. But I am completely lost in Python, it goes way beyond my expertise, @peterzhuamazon could you give me a hand here? I can definitely implement the `image` support in manifest but will drown in `dependencies` + build environment manipulation.
> 
> I'd be happy to help. Try getting the image going and I can take care of dependences on top of that?
> 
> > @dblock thank you, I was looking also into `https://github.com/opensearch-project/OpenSearch/blob/main/Jenkinsfile` and it seems like it uses predefined agents `search-cloud-ec2-c518xlarge`, which we have to rebuild out of new images, any hints / people who could help with that?
> 
> @peternied @peterzhuamazon ?

Are you trying to ask what change have I done to that Jenkins Agent?

2021-10-20 23:08 UTC, dblock approved these changes
👏 nice work @reta, you just learned Python :)

2021-10-20 23:08 UTC, dblock commented on manifests/1.2.0/opensearch-1.2.0.yml
> +     args: "-e JAVA_HOME=/usr/lib/jvm/adoptopenjdk-14-hotspot"
we are for 2.0, see below

2021-10-20 23:26 UTC, reta commented
> Are you trying to ask what change have I done to that Jenkins Agent?

@peterzhuamazon more precisely, if this agents uses the same CI multi-jdk images you've published or is uses different ones?

2021-10-21 12:50 UTC, dblock commented on jenkins/opensearch-dashboards/Jenkinsfile
> +        stage('detect Docker image + args to use for the build') {
Someone will have to show us how :)

2021-10-21 12:59 UTC, reta commented on jenkins/opensearch-dashboards/Jenkinsfile
> +        stage('detect Docker image + args to use for the build') {
It sadly needs access to Jenkins instance and happens at job / pipeline level

2021-10-21 16:00 UTC, peterzhuamazon commented
> > They use the one you define in the Jenkinsfile.
> 
> @peterzhuamazon Sorry, I am not following, this is a complete Jenkinsfile (https://github.com/opensearch-project/OpenSearch/blob/main/Jenkinsfile), it uses labelled agents which have to be provided by Jenkins.
> 
> ```
> pipeline {
>     agent { label 'search-cloud-ec2-c518xlarge' }
> 
> 
>     stages {
>         stage('Build') {
>             steps {
>                 echo 'Building..'
>                 // Disable backward compability tasks
>                 sh './gradlew check --no-daemon --no-scan -Pbwc_tests_enabled=false'
>             }
>         }
>         stage('Test') {
>             steps {
>                 echo 'Testing..'
>             }
>         }
>         stage('Deploy') {
>             steps {
>                 echo 'Deploying..'
>             }
>         }
>     }
> }
> ```

The docker image will run in those agent you defined.
No need to change the agent as long as you define the docker image, they will for sure run in those Jenkins agent.
The Jenkins agent act as a Docker Host.

https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-dashboards/Jenkinsfile#L27-L32

2021-10-21 17:47 UTC, merged