Added alerting-dashboard-plugin to manifest 1.2.0.
opensearch-project/opensearch-build pull request #874
Opened 2021-11-03 06:14 UTC by AWSHurneyt

### Description
Adding alerting-dashboard-plugin to manifest 1.2.0.
 
### Issues Resolved
[issue118](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/118)
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-11-03 17:15 UTC, dblock commented
Rebase this on top of #876, I think this is an unrelated failure.

2021-11-03 17:31 UTC, kavilla approved these changes

2021-11-03 17:44 UTC, dblock requested changes
This YAML is invalid, so tests are failing as expected.

2021-11-04 07:19 UTC, AWSHurneyt commented
Closing this PR in favor of [PR 886](https://github.com/opensearch-project/opensearch-build/pull/886).

2021-11-04 07:19 UTC, closed without merging