[Dashboards] update 1.1 manifest to use tags
opensearch-project/opensearch-build pull request #901
Opened 2021-11-06 03:00 UTC by kavilla

### Description
Update OpenSearch Dashboards 1.1.0 manifest to use git tags.

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
n/a
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-11-06 12:03 UTC, dblock commented
In #896 we replaced these with saying `tags` explicitly, should do it here too please.

2021-11-08 16:06 UTC, peterzhuamazon requested changes
Block this as @dblock already points out we should make sure tags are used:
https://github.com/opensearch-project/opensearch-build/pull/896

2021-11-08 18:01 UTC, dblock approved these changes

2021-11-08 18:05 UTC, gaiksaya approved these changes

2021-11-08 18:12 UTC, merged